/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_corgitaco_NoiseGenerator */

#ifndef _Included_dev_corgitaco_NoiseGenerator
#define _Included_dev_corgitaco_NoiseGenerator
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     dev_corgitaco_NoiseGenerator
	 * Method:    getUniformGrid3DPointer
	 * Signature: (IIIIIFI)[J
	 */
	JNIEXPORT jlongArray JNICALL Java_dev_corgitaco_NoiseGenerator_getUniformGrid3DPointer
	  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jfloat, jint);

	/*
	 * Class:     dev_corgitaco_NoiseGenerator
	 * Method:    freeUniformGrid3DPointer
	 * Signature: ([J)V
	 */
	JNIEXPORT void JNICALL Java_dev_corgitaco_NoiseGenerator_freeUniformGrid3DPointer
	  (JNIEnv *, jclass, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
